# Generated by Django 5.0.7 on 2024-07-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('name', 'reservation_date', 'reservation_time')},
        ),
    ]
